- hosts: localhost
  tasks:
  - name: Load cryo repo
    shell: |
      VERSION=1.25
      OS=CentOS_8
      curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/devel:kubic:libcontainers:stable.repo
      curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo

  - name: Install cri-o 
    yum:
      name:
        - "cri-o"
        - "cri-tools"
      state: present

  - name: Start cri-o 
    shell: |
      systemctl daemon-reload
      systemctl enable crio --now
      systemctl enable kubelet --now

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |     
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Create disable swap fstab
    shell: line=$(grep -n -m 1 swap /etc/fstab | cut -d ":" -f 1) && sed -e "${line}s/^/#/" /etc/fstab > /etc/fstab.bk

  - name: Disabled Swap
    shell: cp /etc/fstab.bk /etc/fstab

  - name: Active netfiter
    shell: modprobe br_netfilter

  - name: Disable SWAP
    shell: swapoff -a

  - name: disable firewall
    shell: systemctl stop firewalld && systemctl disable firewalld && systemctl mask --now firewalld

  - name: Install kubeadm kubelet kubectl
    yum:
      name: 
        - kubeadm 
        - kubelet
        - kubectl
      state: present 

  - name: Enable systemctl enable kubelet.service
    shell: systemctl enable kubelet.service

  - name: Enable br_netfilter
    shell: |
      cat << EOF | sudo tee /etc/modules-load.d/k8s.conf
      br_netfilter
      EOF

  - name: Enable bridge nf call k8s.conf
    shell: |
      cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
      EOF

  - name: sysctl
    shell: sudo sysctl --system